# Generated by Django 3.0.3 on 2020-02-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninjutsu', models.IntegerField()),
                ('taijutsu', models.IntegerField()),
                ('genjutsu', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('handseals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('clan', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.CharField(blank=True, max_length=64, null=True)),
                ('photo', models.ImageField(upload_to='assets')),
                ('abilities', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Abilities')),
            ],
        ),
    ]
