# Generated by Django 3.0.3 on 2020-02-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Abilities'),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
    ]
