# Generated by Django 3.0.3 on 2020-02-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200206_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abilities',
        ),
        migrations.AddField(
            model_name='character',
            name='genjutsu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='handseals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ninjutsu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='stamina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='taijutsu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
    ]
