# Generated by Django 3.0.3 on 2020-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200208_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ninjarank',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
