# Generated by Django 3.0.3 on 2020-02-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200214_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='baseoverall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=155, null=True),
        ),
    ]
